# Generated by Django 5.2.1 on 2025-05-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(
                        db_index=True,
                        help_text="Группа меню, напр. 'main_menu'",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "named_url",
                    models.CharField(
                        blank=True, help_text="Имя url из urls.py", max_length=100
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="Либо явный URL", max_length=200
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_name", "parent__id", "order"],
                "unique_together": {("menu_name", "id")},
            },
        ),
    ]
