# Generated by Django 5.2.1 on 2025-05-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Используется для {% draw_menu 'name' %}",
                        max_length=50,
                        unique=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Заголовок"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ("order",)},
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(
                blank=True,
                help_text="например app:view_name",
                max_length=100,
                verbose_name="именованный URL",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="порядок"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=100, verbose_name="заголовок пункта"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="например, /contacts/",
                max_length=200,
                verbose_name="явный URL",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.menu",
                verbose_name="меню",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="menu_name",
        ),
    ]
